Homework1
made-ml-in-prod-2022/lovets18 pull request #2
Opened 2022-05-10 20:45 UTC by lovets18

HM1
TECHNOPARK

2022-05-31 14:45 UTC, SVizor42 commented on ml_project/main.py
> +from ml_project.dataclasses.config_params_read import read_params_config
Нужно стараться разделять стандартные и локальные импорты. Обрати внимание на это и в других модулях, плиз

2022-05-31 14:48 UTC, SVizor42 commented on ml_project/preprocess.py
> +        data = data.drop(["chol", "restecg"], axis=1)
Хардкодить имена признаков - не очень хорошая практика :) Лучше вынести признаки в отдельную часть конфига. Или хотя бы использовать константы

2022-05-31 14:51 UTC, SVizor42 commented on ml_project/train.py
> +def create_model(params: PipelineParams):
Return type?

2022-05-31 21:19 UTC, SVizor42 commented on ml_project/train.py
> +            'lgbm',
xgbm etc.

2022-05-31 21:26 UTC, SVizor42 commented on ml_project/predict.py
> +    with open(predict_params.pathes.model_path, 'rb') as file:
Все-таки загружать модель при каждом предикте не очень эффективно. Передай ее просто в качестве аргумента

2022-05-31 21:27 UTC, SVizor42 commented on ml_project/predict.py
> +    df_x = preprocess_data(df_x,
`df_x` - я бы советовал избегать таких идентификаторов в продакшен коде

2022-05-31 21:46 UTC, SVizor42 requested changes
Что нужно поправить:
1. Добавить `pycache` в `.gitignore`
2. `tests.py` положить в папку `tests`

Общие рекомендации:
1. Самооценку лучше добавлять в сам PR
2. Было бы удобно вынести в конфиг возможность включать-отключать отдельные этапы (обучение, инференс)

2022-06-08 23:10 UTC, lovets18 commented
Прошу прощения, завалы на учебе и работе, поправлю в течение пары дней

2022-06-10 09:29 UTC, lovets18 commented on ml_project/main.py
> +from ml_project.dataclasses.config_params_read import read_params_config
Сделал \n\n между стандартными и локальными импортами

2022-06-10 09:30 UTC, lovets18 commented on ml_project/preprocess.py
> +        data = data.drop(["chol", "restecg"], axis=1)
Признаки для удаления теперь пишутся в drop_low_cor в конфиге

2022-06-10 09:30 UTC, lovets18 commented on ml_project/train.py
> +def create_model(params: PipelineParams):
Возвращает Pipeline

2022-06-10 09:31 UTC, lovets18 commented on ml_project/train.py
> +            'lgbm',
Скорректировал названия шагов в пайплайнах

2022-06-10 09:31 UTC, lovets18 commented on ml_project/predict.py
> +    with open(predict_params.pathes.model_path, 'rb') as file:
Модель теперь передается в качестве аргумента model

2022-06-10 09:32 UTC, lovets18 commented on ml_project/predict.py
> +    df_x = preprocess_data(df_x,
Поменял имя переменной на data_features

2022-06-10 09:34 UTC, lovets18 commented
Добавил pycache в gitignore, перенес тесты в папку tests, добавил возможность включения/отключения этапов в конфиге (stages)

2022-06-11 20:55 UTC, SVizor42 approved these changes
Ок. Если нет возражений, можешь сливать ветку.

**Сумма: 28.5 баллов** (п. 9 - 3/3)

2022-06-11 22:02 UTC, merged